# Generated by Django 3.1.2 on 2020-11-04 22:15

from django.db import migrations, models

def forward(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    for student in Student.objects.all():
        student.teachers.add(student.teacher)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_teachers'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
